install.packages('emmeans')
install.packages('lme4')
library(emmeans)
library(lme4)
library(readr)
data <- read_csv("difficulty.csv")
attach(data)
levels <- as.factor(levelNumber)
id <- as.factor(prolificPID)
difficultyModel <- lmer(difficultyValue ~ levels + (1|id))
stuckModel <- lmer(stuckValue ~ levels + (1|id))
emmeans(difficultyModel, pairwise ~ levels)
emmeans(stuckModel, pairwise ~ levels)